corrct mistakes spelling and added some more lines to ook readme attractive.
halomod/hmf pull request #96
Opened 2020-10-01 06:37 UTC by bidderlol

2020-10-01 14:13 UTC, steven-murray requested changes

2020-10-01 14:13 UTC, steven-murray commented on README.rst
> +or otherwise. The best way to see these is to do:
The double-colon is required for RST.

2020-10-01 14:13 UTC, steven-murray commented on README.rst
> +At last it is one of the finest calculators whiuch helps you to perform calculation at fast speed .
Thank you for the positive feedback! I don't think I can put this in my readme though :-)

2020-10-02 15:36 UTC, bidderlol commented
Dont keep but dont mark.it invalid pls

On Thu, Oct 1, 2020, 19:43 Steven Murray <notifications@github.com> wrote:

> *@steven-murray* requested changes on this pull request.
> ------------------------------
>
> In README.rst
> <https://github.com/steven-murray/hmf/pull/96#discussion_r498276143>:
>
> > @@ -66,7 +66,7 @@ Note that all parameters have (what I consider reasonable) defaults. In particul
>  this will return a Tinker (2008) mass function between
>  10^10 and 10^15 solar masses, at z=0 for the default PLANCK15 cosmology.
>  Nevertheless, there are several parameters which can be input, either cosmological
> -or otherwise. The best way to see these is to do::
> +or otherwise. The best way to see these is to do:
>
> The double-colon is required for RST.
> ------------------------------
>
> In README.rst
> <https://github.com/steven-murray/hmf/pull/96#discussion_r498276636>:
>
> > @@ -112,3 +112,5 @@ Attribution
>  Please cite `Murray, Power and Robotham (2013)
>  <https://arxiv.org/abs/1306.6721>`_ and/or https://ascl.net/1412.006 (whichever is more appropriate) if you find this
>  code useful in your research. Please also consider starring the GitHub repository.
> +At last it is one of the finest calculators whiuch helps you to perform calculation at fast speed .
>
> Thank you for the positive feedback! I don't think I can put this in my
> readme though :-)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/steven-murray/hmf/pull/96#pullrequestreview-500390445>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQSBIL5KCYUA57R4THS5G6LSISFCDANCNFSM4SAAAZCQ>
> .
>

2024-07-24 14:24 UTC, closed without merging